### ISSUE TITLE
Create top nav social links

### ISSUE THREAD

**Issue by jbarratt77** [The-Great-Ape/main-site#2]
![image](https://user-images.githubusercontent.com/30458569/118686719-2c6e4d80-b7fc-11eb-8338-808e3b4e65cf.png)

Replicate the social links from the old site on the new site

**Comment by tommaay** [comment]
Got the icons added and the links working. I'm having issues pushing my changes though and it's getting late my time so I will fix my permissions tomorrow morning.

<img width="249" alt="Screen Shot 2021-05-18 at 9 31 05 PM" src="https://user-images.githubusercontent.com/26946743/118756742-6ea98600-b820-11eb-8761-e9349cacbdc4.png">
