### ISSUE TITLE
Create top nav links

### ISSUE THREAD

**Issue by jbarratt77** [The-Great-Ape/main-site#5]
![image](https://user-images.githubusercontent.com/30458569/118687163-9c7cd380-b7fc-11eb-9686-801afb332a98.png)

- Tokenomics (hash link to further down the page)
- Roadmap (currently unlinked)
- Litepaper dropdown (links to PDFs)

**Comment by tommaay** [comment]
Added the links but still need to hook up the link to the section and litepapers
